version: '3.8'

services:
  usersInfoDB:
    container_name: usersInfoDB
    image: postgres
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: master
      POSTGRES_DB: usersInfoDB
    ports:
      - "5433:5432" # Формат: "HOST_PORT:CONTAINER_PORT"
    
    volumes:
      - usersInfoDB-vol:/var/lib/postgresql/data

volumes:
  usersInfoDB-vol:


